AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PowerShell based AWS Lambda application with API Gateway Trigger (REST).
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Handler::Handler.Bootstrap::ExecuteFunction
      Runtime: dotnetcore3.1
      CodeUri: s3://lambda-artifacts-991ee7fe2657edd4/3e671d25a1aafd13c1fd9b0a7b3dde92
      Description: Call the AWS Lambda API
      Timeout: 30
      MemorySize: 512
      Events:
        GetAPIEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /test
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
