---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: PowerShell based AWS Lambda application with API Gateway Trigger (HTTP).
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Handler::Handler.Bootstrap::ExecuteFunction
      Runtime: dotnetcore3.1
      CodeUri: function/function.zip
      Description: Call the AWS Lambda API
      Timeout: 30
      MemorySize: 512
      Events:
        GetAPIEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /test
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active